### ISSUE TITLE
两个BUG

### ISSUE THREAD

**Issue by yuyao110120** [Nododo/ADo_MinToMaxSlider#1]
1. 计算百分比的时候，使用int强制截尾浮点数的计算方式最好加0.5在截尾，这样可以做到四舍五入，你现在的计算方法，很难将滑块跳到100，因为哪怕是99.9999也会被认为是99
2. 绘制圆形滑块fill填充白色的时候，使用的椭圆绘制rect要和绘制灰色圆环的rect保持一致，要不然会有一点错位

**Comment by Nododo** [comment]
好的 多谢你提出的要求  我有时间就完善一下

**Comment by Nododo** [comment]
第一个bug 还是按原来的方式走, 如果最大值不是100 而是500,1000,如果加0.5,误差也就大了起来,第二个bug已修复.
